# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.0
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError('Python 2.7 or later required')

# Import the low-level C/C++ module
if __package__ or '.' in __name__:
    from . import _twittertext
else:
    import _twittertext

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if name == "thisown":
        return self.this.own(value)
    if name == "this":
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if not static:
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if name == "thisown":
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class TwitterTextParseResults(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    weighted_length = property(_twittertext.TwitterTextParseResults_weighted_length_get, _twittertext.TwitterTextParseResults_weighted_length_set)
    permillage = property(_twittertext.TwitterTextParseResults_permillage_get, _twittertext.TwitterTextParseResults_permillage_set)
    is_valid = property(_twittertext.TwitterTextParseResults_is_valid_get, _twittertext.TwitterTextParseResults_is_valid_set)
    display_text_range = property(_twittertext.TwitterTextParseResults_display_text_range_get, _twittertext.TwitterTextParseResults_display_text_range_set)
    valid_text_range = property(_twittertext.TwitterTextParseResults_valid_text_range_get, _twittertext.TwitterTextParseResults_valid_text_range_set)

    def __init__(self, weighted_length, permillage, is_valid, display_text_range, valid_text_range):
        _twittertext.TwitterTextParseResults_swiginit(self, _twittertext.new_TwitterTextParseResults(weighted_length, permillage, is_valid, display_text_range, valid_text_range))

    def __eq__(self, other):
        return _twittertext.TwitterTextParseResults___eq__(self, other)

    def __ne__(self, other):
        return _twittertext.TwitterTextParseResults___ne__(self, other)
    __swig_destroy__ = _twittertext.delete_TwitterTextParseResults

# Register TwitterTextParseResults in _twittertext:
_twittertext.TwitterTextParseResults_swigregister(TwitterTextParseResults)
cvar = _twittertext.cvar
MAX_TWEET_LENGTH = cvar.MAX_TWEET_LENGTH
MAX_URL_LENGTH = cvar.MAX_URL_LENGTH


def parse(text, config, extract_urls):
    return _twittertext.parse(text, config, extract_urls)


