[package]
name = "twitter_text_bindings_cargo"
version = "0.1.0"
authors = ["Robert Sayre <sayrer@gmail.com>"]
edition = "2018"
features = ["std"]

[dependencies]
clap = "2.33.0"
proc-macro-error = {version = "=0.4.8" }
log = {version = "=0.4.0", features = ["std"]}
cxx = { git = "https://github.com/dtolnay/cxx", rev = "71912c3f11c9a5928b6bbfd1d26bad82a1bed3f7" }
cxxbridge-cmd = { git = "https://github.com/dtolnay/cxx", path = "", rev = "71912c3f11c9a5928b6bbfd1d26bad82a1bed3f7" }
pest = "2.1.2"
pest_derive = "2.1.0"
unicode-normalization = "0.1.12"
idna = "0.1.5"
lazy_static = "1.4.0"
serde = "1.0.104"
serde_derive = "1.0.104"
serde_json = "1.0.45"
serde_yaml = "0.7"

[lib]
path = "fake_lib.rs"

[raze]
workspace_path = "//rust_bindings/cargo"
output_buildfile_suffix = "BUILD.bazel"

[raze.crates.log.'0.4.0']
additional_flags = [
    "--cfg", "std",
]

[raze.crates.proc-macro2.'1.0.21']
additional_flags = [
#    "--cfg", "u128",
    "--cfg=use_proc_macro",
    "--cfg=wrap_proc_macro",
"--cfg=span_locations",
]

[raze.crates.cxx.'0.4.6']
data_attr = 'glob(["**/*.h", "**/*.cc"])'
extra_aliased_targets = [
    "cxx_cc_library"
]

[raze.crates.cxxbridge-cmd.'0.4.6']
additional_flags = [
    "--cfg", "procmacro2_semver_exempt",
]
data_attr = 'glob(["**/*.h"])'
extra_aliased_targets = [
    "cargo_bin_cxxbridge"
]