[package]
name = "twitter_text_bindings_cargo"
version = "0.1.0"
authors = ["Robert Sayre <sayrer@gmail.com>"]
edition = "2018"
features = ["std"]

[dependencies]
clap = "2.33.3"
proc-macro-error = {version = "=0.4.8" }
log = {version = "=0.4.0", features = ["std"]}
cxx = "1.0.18"
cxxbridge-cmd ="1.0.18"
pest = "2.1.2"
pest_derive = "2.1.0"
unicode-normalization = "0.1.12"
idna = "0.1.5"
lazy_static = "1.4.0"
serde = "1.0.104"
serde_derive = "1.0.104"
serde_json = "1.0.45"
serde_yaml = "0.7"

[lib]
path = "fake_lib.rs"

[package.metadata.raze]
gen_mode = "vendor"
workspace_path = "//rust_bindings/cargo"

#[raze]
#workspace_path = "//rust_bindings/cargo"
#output_buildfile_suffix = "BUILD.bazel"

[package.metadata.raze.crates.log.'0.4.0']
additional_flags = [
    "--cfg", "std",
]

[package.metadata.raze.crates.proc-macro2.'1.0.24']
additional_flags = [
    "--cfg=use_proc_macro",
    "--cfg=wrap_proc_macro",
    "--cfg=span_locations",
]

[package.metadata.raze.crates.cxx.'1.0.18']
data_attr = 'glob(["**/*.h", "**/*.cc"])'
extra_aliased_targets = [
    "cxx_cc_library"
]

[package.metadata.raze.crates.cxxbridge-cmd.'1.0.18']
additional_flags = [
    "--cfg", "procmacro2_semver_exempt",
]
data_attr = 'glob(["**/*.h"])'
extra_aliased_targets = [
    "cargo_bin_cxxbridge"
]
