[package]
name = "twitter_text_bindings_cargo"
version = "0.1.0"
authors = ["Robert Sayre <sayrer@gmail.com>"]
edition = "2018"
features = ["std"]

[dependencies]
clap = "2.33.0"
proc-macro-error = {version = "=0.4.8" }
log = {version = "=0.4.0", features = ["std"]}
cxx = { git = "https://github.com/dtolnay/cxx", rev = "291a8b87a16e0c738b8caaeae1d28670416dda9e" }
cxxbridge-cmd = { git = "https://github.com/dtolnay/cxx", path = "", rev = "291a8b87a16e0c738b8caaeae1d28670416dda9e" }
pest = "2.1.2"
pest_derive = "2.1.0"
unicode-normalization = "0.1.12"
idna = "0.1.5"
lazy_static = "1.4.0"
serde = "1.0.104"
serde_derive = "1.0.104"
serde_json = "1.0.45"
serde_yaml = "0.7"

[lib]
path = "fake_lib.rs"

[raze]
workspace_path = "//rust_bindings/cargo"
output_buildfile_suffix = "BUILD.bazel"

[raze.crates.log.'0.4.0']
additional_flags = [
    "--cfg", "std",
]

[raze.crates.proc-macro2.'1.0.19']
additional_flags = [
#    "--cfg", "u128",
    "--cfg=use_proc_macro",
    "--cfg=wrap_proc_macro",
"--cfg=span_locations",
]

#[raze.crates.syn.'1.0.30']
#additional_flags = [
#    "--cfg", "syn_can_match_trailing_dollar",
#    "--cfg", "syn_can_use_thread_id",
#    "--cfg", "syn_can_use_associated_constants",
#    "--cfg", "syn_can_call_macro_by_path",
#    "--cfg", "syn_disable_nightly_tests",
#]

[raze.crates.rustversion.'1.0.2']
gen_buildrs = true

[raze.crates.proc-macro-error.'1.0.2']
gen_buildrs = true
additional_flags = [
	"--cfg=use_fallback"
]

[raze.crates.proc-macro-error-attr.'1.0.2']
gen_buildrs = true
additional_flags = [
	"--cfg=use_fallback"
]

[raze.crates.cbindgen.'0.12.2']
extra_aliased_targets = [
    "cargo_bin_cbindgen",
]

[raze.crates.cxx.'0.3.4']
data_attr = 'glob(["**/*.h", "**/*.cc"])'
extra_aliased_targets = [
    "cxx_cc_library"
]


[raze.crates.cxxbridge-cmd.'0.3.4']
additional_flags = [
    "--cfg", "procmacro2_semver_exempt",
]
data_attr = 'glob(["**/*.h"])'
extra_aliased_targets = [
    "cargo_bin_cxxbridge"
]