#!/bin/bash
# Insert generated TLD grammar into twitter_text.pest after the marker comment
set -e

INPUT_PEST="$1"
GENERATED_TLD="$2"
OUTPUT_PEST="$3"

# Find the line with "This rule is generated by tld_gen.py"
MARKER_LINE=$(grep -n "This rule is generated by tld_gen.py" "$INPUT_PEST" | cut -d: -f1)

if [ -z "$MARKER_LINE" ]; then
    echo "Error: Could not find marker comment in $INPUT_PEST" >&2
    exit 1
fi

# Find the next line (which should be "// See the comments there.")
NEXT_LINE=$((MARKER_LINE + 1))

# Extract everything before the insertion point
head -n "$NEXT_LINE" "$INPUT_PEST" > "$OUTPUT_PEST"

# Append the generated TLD grammar
cat "$GENERATED_TLD" >> "$OUTPUT_PEST"

# Find where the old tld_list ends (look for the closing brace at the same indentation level)
# We need to skip from "tld_list = _{" to the matching "}"
START_SKIP=$((NEXT_LINE + 1))
awk -v start="$START_SKIP" 'NR >= start && /^}/ {found=NR; exit} END {print found}' "$INPUT_PEST" > /tmp/end_line.txt
END_LINE=$(cat /tmp/end_line.txt)

if [ -z "$END_LINE" ]; then
    echo "Error: Could not find end of tld_list rule" >&2
    exit 1
fi

# Append everything after the old tld_list
tail -n +$((END_LINE + 1)) "$INPUT_PEST" >> "$OUTPUT_PEST"

echo "Successfully inserted TLD grammar into $OUTPUT_PEST" >&2
