# Copyright 2025 Robert Sayre
# Licensed under the Apache License, Version 2.0
# http://www.apache.org/licenses/LICENSE-2.0

import argparse
import sys

import yaml


def main():
    parser = argparse.ArgumentParser(
        description="Generate TLD PHF hash set for Rust"
    )
    parser.add_argument(
        "--input", required=True, help="Input YAML file containing TLDs"
    )
    parser.add_argument(
        "--output", required=True, help="Output file for generated tlds.rs"
    )
    args = parser.parse_args()

    with open(args.input, "r", encoding="utf-8") as stream:
        try:
            tld_structure = yaml.safe_load(stream)
        except yaml.YAMLError as exc:
            print(exc, file=sys.stderr)
            sys.exit(1)

    tlds = set()
    for kind in tld_structure.values():
        for element in kind:
            idna = element.encode("idna").decode("ascii")
            if idna != element:
                tlds.add(idna)
            tlds.add(element.lower())

    # Separate into ASCII, unicode, and punycode for organized output
    ascii_tlds = sorted(t for t in tlds if all(ord(c) < 128 for c in t) and not t.startswith("xn--"))
    unicode_tlds = sorted(t for t in tlds if any(ord(c) >= 128 for c in t))
    punycode_tlds = sorted(t for t in tlds if t.startswith("xn--"))

    with open(args.output, "w", encoding="utf-8") as out:
        out.write(FILE_HEADER)

        # Write phf_set entries
        for tld in ascii_tlds:
            out.write(f'    "{tld}",\n')
        for tld in unicode_tlds:
            out.write(f'    "{tld}",\n')
        out.write("    // Punycode TLDs (IDN TLDs in ASCII-compatible encoding)\n")
        for tld in punycode_tlds:
            out.write(f'    "{tld}",\n')

        out.write(FILE_FOOTER)

    print(
        f"Generated {args.output} with {len(tlds)} TLDs "
        f"({len(ascii_tlds)} ASCII, {len(unicode_tlds)} Unicode, "
        f"{len(punycode_tlds)} Punycode)",
        file=sys.stderr,
    )


FILE_HEADER = """\
// Copyright 2025 Robert Sayre
// Licensed under the Apache License, Version 2.0
// http://www.apache.org/licenses/LICENSE-2.0

//! TLD lookup using a compile-time perfect hash map.
//!
//! This module provides O(1) TLD validation, replacing the O(n)
//! Pest grammar alternation.
//!
//! This file is generated by tld_gen_phf.py from tld_lib.yml.
//! Do not edit by hand.

use phf::phf_set;

/// A compile-time perfect hash set of all valid TLDs.
/// Case-insensitive matching is handled by lowercasing input before lookup.
pub static TLDS: phf::Set<&'static str> = phf_set! {
"""

FILE_FOOTER = """\
};

/// Check if a string is a valid TLD.
/// The input should be lowercase.
#[inline]
pub fn is_valid_tld(tld: &str) -> bool {
    TLDS.contains(tld)
}

/// Maximum TLD length in bytes (longest is "சிங்கப்பூர்" at 33 bytes)
const MAX_TLD_LEN: usize = 64;

/// Check if a string is a valid TLD, case-insensitively.
/// Uses a stack-allocated buffer for lowercase conversion to avoid heap allocations.
#[inline]
pub fn is_valid_tld_case_insensitive(tld: &str) -> bool {
    // Fast path: if already lowercase ASCII, check directly
    if tld.bytes().all(|b| !b.is_ascii_uppercase()) {
        return TLDS.contains(tld);
    }

    // Need to lowercase - use stack buffer if small enough
    if tld.len() <= MAX_TLD_LEN {
        let mut buf = [0u8; MAX_TLD_LEN];
        let mut i = 0;
        for c in tld.chars() {
            for lc in c.to_lowercase() {
                let len = lc.len_utf8();
                if i + len > MAX_TLD_LEN {
                    // Overflow - fall back to heap allocation
                    return TLDS.contains(&tld.to_lowercase());
                }
                lc.encode_utf8(&mut buf[i..]);
                i += len;
            }
        }
        // Safety: we only wrote valid UTF-8 chars
        let lowered = unsafe { std::str::from_utf8_unchecked(&buf[..i]) };
        TLDS.contains(lowered)
    } else {
        // TLD too long - fall back to heap allocation (shouldn't happen with valid TLDs)
        TLDS.contains(&tld.to_lowercase())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_common_tlds() {
        assert!(is_valid_tld("com"));
        assert!(is_valid_tld("org"));
        assert!(is_valid_tld("net"));
        assert!(is_valid_tld("uk"));
        assert!(is_valid_tld("io"));
    }

    #[test]
    fn test_unicode_tlds() {
        assert!(is_valid_tld("中国"));
        assert!(is_valid_tld("рф"));
        assert!(is_valid_tld("한국"));
    }

    #[test]
    fn test_punycode_tlds() {
        assert!(is_valid_tld("xn--p1ai")); // .рф (Russia)
        assert!(is_valid_tld("xn--wgbh1c")); // .مصر (Egypt)
        assert!(is_valid_tld("xn--mgbaam7a8h")); // .امارات (UAE)
    }

    #[test]
    fn test_invalid_tlds() {
        assert!(!is_valid_tld("invalid"));
        assert!(!is_valid_tld("notarealtld"));
        assert!(!is_valid_tld(""));
    }
}
"""


if __name__ == "__main__":
    main()
