[package]
name = "twitter_text_config"
version = "0.1.0"
authors = ["Robert Sayre <sayrer@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"