package(default_visibility = ["//visibility:public"])

filegroup(
    name = "twitter_text",
    srcs = glob(["twitter-text/**/*.rs", "parser/**/*.rs", "config/**/*.rs"]),
)

filegroup(
    name = "twitter_text_crate",
    srcs = ["twitter-text/Cargo.toml"],
)

filegroup(
    name = "highlighter",
    srcs = ["twitter-text/src/lib.rs"],
)