language = "C++"

############## Options for Wrapping the Contents of the Header #################

include_version = true
include_guard = "twitter_text_ffi_h"
namespaces = ["twittertext", "ffi"]
sys_includes = []

# This was meant to live in a concatenated middle file
includes = []
