no_includes = false

############################ Code Style Options ################################

braces = "SameLine"
line_length = 100
tab_width = 2
documentation_style = "auto"

############################# Codegen Options ##################################

style = "both"

[defines]
# "target_os = freebsd" = "DEFINE_FREEBSD"
# "feature = serde" = "DEFINE_SERDE"

[export]
item_types =  ["constants", "globals", "enums", "structs", "unions", "typedefs", "opaque", "functions"]
renaming_overrides_prefixing = false

[export.rename]

[export.body]

[fn]
rename_args = "None"
args = "auto"

[struct]
derive_constructor = true
derive_eq = true
derive_neq = true
derive_lt = false
derive_lte = false
derive_gt = false
derive_gte = false

[enum]
rename_variants = "None"
add_sentinel = false
prefix_with_name = false
derive_helper_methods = false
derive_const_casts = false
derive_mut_casts = false
derive_tagged_enum_destructor = false
derive_tagged_enum_copy_constructor = false

[const]
allow_static_const = true

[macro_expansion]
bitflags = false

############## Options for How Your Rust library Should Be Parsed ##############

[parse]
parse_deps = true
include = ["twitter-text", "twitter_text_config", "pest"]
#exclude = []
clean = true
extra_bindings = []

[parse.expand]
crates = []
all_features = true
default_features = true
features = []
